# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bac7b50dc214c7c7edbd7728130bf1e6b65986bbb734d5855750da7b9ce9c7462c630c63c18a4b207799762f186f567955c8c1361e168e5fcab0eef9c96650c

test:
  secret_key_base: 13edeadda5b1a2a25c3d5f05181b86fe12306ef3fe466146fa0590ab846c1399c25b7050c69ab3ac71d803fc943931b367351536f95b6d5385ec847f088f1761

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
